# Simple configuration for an HTTP proxy listening on port 80 on all
# interfaces and forwarding requests to a single backend "servers" with a
# single server "server1" listening on 127.0.0.1:8000
global
#    daemon
    maxconn 256

defaults
    mode http
    timeout connect 5000ms
    timeout client 50000ms
    timeout server 50000ms

frontend http-in
    bind *:80
    default_backend servers

backend servers
    server server1 172.17.0.1:8080 maxconn 32
# 172.17.0.1 --> docker host IP (docker0 inet interface)


## The same configuration defined with a single listen block. Shorter but
## less expressive, especially in HTTP mode.
#global
#    daemon
#    maxconn 256

#defaults
#    mode http
#    timeout connect 5000ms
#    timeout client 50000ms
#    timeout server 50000ms

#listen http-in
#    bind *:80
#    server server1 127.0.0.1:8000 maxconn 32
